2020-11-27 18:23:08,713 - E:\Chargespot-rq\API_Automation\Testcase\test_codeLogin.py[line:21] - ERROR: 数据不一致
2020-11-27 18:26:16,310 - E:\Chargespot-rq\API_Automation\Testcase\test_codeLogin.py[line:21] - ERROR: 数据不一致
2020-11-27 18:27:43,012 - E:\Chargespot-rq\API_Automation\Testcase\test_codeLogin.py[line:21] - ERROR: 数据不一致
