2021-01-12 15:21:07,449 - E:\Chargespot-rq\API_Automation\Testcase\test_codeLogin.py[line:22] - ERROR: 数据不一致
2021-01-12 15:25:52,887 - E:\Chargespot-rq\API_Automation\Testcase\test_codeLogin.py[line:22] - ERROR: 数据不一致
2021-01-12 15:31:05,390 - E:\Chargespot-rq\API_Automation\Testcase\test_codeLogin.py[line:22] - ERROR: 数据不一致
2021-01-12 15:34:17,208 - E:\Chargespot-rq\API_Automation\Testcase\test_codeLogin.py[line:22] - ERROR: 数据不一致
2021-01-12 15:35:03,323 - E:\Chargespot-rq\API_Automation\Testcase\test_codeLogin.py[line:22] - ERROR: 数据不一致
2021-01-12 15:40:23,590 - E:\Chargespot-rq\API_Automation\Testcase\test_codeLogin.py[line:22] - ERROR: 数据不一致
